#!/bin/bash
# This is our first script.
echo 'Begin!'
source activate dense
for i in {1..1705}
do
    /home/cjy/.conda/envs/dense/bin/python2.7 /home/cjy/GNN_demo/hand_GNN.py $i 10 0.001
done

for i in {1..1705}
do
    /home/cjy/.conda/envs/dense/bin/python2.7 /home/cjy/GNN_demo/hand_GNN.py $i 10 0.0001
done

for i in {1..1705}
do
    /home/cjy/.conda/envs/dense/bin/python2.7 /home/cjy/GNN_demo/hand_GNN.py $i 10 0.00001
done

